Fix build on RISCV
PR #318 forgot to wire parseCPUInfo to parseCPUInfoRISCV on
GOARCH=riscv{,64}, leading to a build/test failure:

./cpuinfo.go:71:9: undefined: parseCPUInfo
./cpuinfo_test.go:222:2: undefined: parseCPUInfo

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>